#!/bin/busybox sh 

#
# Allow vfat to be mounted as ext* instead.
#

# First, fix blkid in a "update-safe" manner.
test -h /sbin/blkid && rm /sbin/blkid && cat > /sbin/blkid <<-'EOF' && chmod +x /sbin/blkid
    #!/bin/busybox sh
	busybox blkid "$@" | sed 's/\(.*KOBOeReader.*TYPE="\)ext./\1vfat/'
EOF

original=$(echo "$@")
filtered=$(echo "$@" | sed -e 's/-t  *vfat//')

if [ "$original" != "$filtered" ]
then
    # vfat first
    /bin/mount "$@" && exit 0
    # otherwise ext*/auto
    filtered=$(echo "$filtered" | sed -e 's/-o  *[^ ]*//')
    exec /bin/mount -t auto -o noatime,nodiratime $filtered
fi

# Everything else:
exec /bin/mount "$@"
